name: Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint-and-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setting up go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.20.1"
      - name:  lint
        run: make lint
      - name: Run unit tests
        run: make test
      - name: Run integration tests
        run: make test-integration

  create-release:
    name: Create Release
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: [lint-and-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        id: changelog
        with:
          github-token: ${{ secrets.github_token }}
          skip-commit: true
          preset: conventionalcommits
      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: Version ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
    outputs:
      tag: ${{ steps.changelog.outputs.tag }}
      skipped: ${{ steps.changelog.outputs.skipped }}
